//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        public int EventDetailsID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string EventDetailes { get; set; }
    
        public virtual User User { get; set; }
    }
}
